Disable react/jsx-curly-brace-presence rule b/c it breaks builds
with this rule enabled we get

/home/runner/work/creditcoin-staking-dashboard/creditcoin-staking-dashboard/src/library/Headers/Connected.tsx
Error:   54:23  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
Error:   69:23  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence

and can't finish the build